export const ENV = {
  appId: process.env.VITE_APP_ID || "apex-banking-portal",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  masterLoginEmail: process.env.MASTER_LOGIN_EMAIL?.trim().toLowerCase() ?? "",
  masterLoginPassword: process.env.MASTER_LOGIN_PASSWORD ?? "",
  masterLoginName: process.env.MASTER_LOGIN_NAME ?? "System Master",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  openRouterApiKey: process.env.OPENROUTER_API_KEY || "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",
  aiModel: process.env.AI_MODEL ?? "google/gemini-2.0-flash-lite-001",
  supabaseUrl: process.env.SUPABASE_URL ?? "",
  supabaseKey: process.env.SUPABASE_SERVICE_ROLE_KEY ?? "",
  serviceBaseUrl: process.env.SERVICE_BASE_URL ?? "",
  serviceApiKey: process.env.SERVICE_API_KEY ?? "",
};
